## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82%,Warning,✓ Met,2026-10-07,0
...,...,...,...,...,...,...,...,...,...,...,...,...
57,4MW24AD059,ZEHA AYESHA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
58,4MW24AD060,AMITH G PALANDYE,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,0%,Critical,30 more,Never,10
59,4MW24AD061,AMOGH BHASKAR NAIK,Data Science & GenAI - 3nd Yr- AI&DS,10,5,5,0,50%,Critical,10 more,2026-10-07,0
60,4MW24AD062,CHANDISH,Data Science & GenAI - 3nd Yr- AI&DS,10,6,4,0,60%,Critical,6 more,2026-10-05,1
61,4MW25AD400,SAMPATH S HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,10,1,9,0,10%,Critical,26 more,2026-09-02,8

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
print(df.head(10))
print(df.shape)
print(df.dtypes)

      Roll No            Student Name                               Subject  \
0   4MW23AD50               SRAJAN  S  Data Science & GenAI - 3nd Yr- AI&DS
1  4MW24AD001       ADITHYA S POOJARY  Data Science & GenAI - 3nd Yr- AI&DS
2  4MW24AD002  ANKITHA PRASANNA NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
3  4MW24AD003          ANUSHA KOTEGAR  Data Science & GenAI - 3nd Yr- AI&DS
4  4MW24AD004      ANVITA RAMESH NAIK  Data Science & GenAI - 3nd Yr- AI&DS
5  4MW24AD005       ARPITHA M THANTRY  Data Science & GenAI - 3nd Yr- AI&DS
6  4MW24AD007                  ASNIYA  Data Science & GenAI - 3nd Yr- AI&DS
7  4MW24AD008   B. G PRARTHANA HEBBAR  Data Science & GenAI - 3nd Yr- AI&DS
8  4MW24AD009      BHARATHRAJ A NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
9  4MW24AD010        BHEEMA KATTIMANI  Data Science & GenAI - 3nd Yr- AI&DS

   Total Classes  Present  Absent  Excused Attendance %    Status  \
0             11        0      11        0           0%  Critical
1             11        7       4        0          64%  Critical
2             11       11       0        0         100%      Safe
3             11       10       1        0          91%      Safe
4             11        9       2        0          82%   Warning
5             11        8       3        0          73%  Critical
6             11       10       1        0          91%      Safe
7             11       10       1        0          91%      Safe
8             11        4       7        0          36%  Critical
9             11        8       3        0          73%  Critical

  Classes Needed (75%) Last Present Date  Consecutive Absences
0              33 more             Never                    11
1               5 more        2026-10-07                     0
2                ✓ Met        2026-10-07                     0
3                ✓ Met        2026-10-07                     0
4                ✓ Met        2026-10-07                     0
5               1 more        2026-10-07                     0
6                ✓ Met        2026-10-07                     0
7                ✓ Met        2026-10-07                     0
8              17 more        2026-10-05                     1
9               1 more        2026-10-07                     0
(62, 12)
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
print(df.isnull().sum())
print(df.isnull().sum()[df.isnull().sum() > 0])
print((df == "Never").sum())

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64
Series([], dtype: int64)
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       5
Consecutive Absences    0
dtype: int64

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('%', 'pct')
print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_(75pct)', 'last_present_date', 'consecutive_absences']

In [8]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('%', 'pct')

df['attendance_pct'] = df['attendance_pct'].astype(str).str.replace('%', '', regex=False).astype(float)

df['last_present_date'] = pd.to_datetime(
    df['last_present_date'].replace('Never', pd.NaT),
    errors='coerce'
)

print(df.dtypes)

roll_no                              str
student_name                         str
subject                              str
total_classes                      int64
present                            int64
absent                             int64
excused                            int64
attendance_pct                   float64
status                               str
classes_needed_(75pct)               str
last_present_date         datetime64[us]
consecutive_absences               int64
dtype: object

#### Section 2: Filtering & Selection

In [9]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
critical_students = df[df['status'] == 'Critical'].sort_values(by='attendance_pct', ascending=True)
print(critical_students)

       roll_no               student_name  \
0    4MW23AD50                  SRAJAN  S
52  4MW24AD054                   UJWAL. K
58  4MW24AD060           AMITH G PALANDYE
36  4MW24AD037     RISHAN FRANCIS MENEZES
45  4MW24AD046              SHARANU PATIL
61  4MW25AD400           SAMPATH S HEBBAR
26  4MW24AD027                    PRAJWAL
30  4MW24AD031            PRAVEEN KUMAR N
8   4MW24AD009         BHARATHRAJ A NAYAK
31  4MW24AD032              PREETH SHETTY
37  4MW24AD038                  RITHESH R
59  4MW24AD061         AMOGH BHASKAR NAIK
10  4MW24AD011                      BINDU
41  4MW24AD042              SANJAN SHETTY
55  4MW24AD057                   VIGHNESH
60  4MW24AD062                   CHANDISH
17  4MW24AD018          MANISH THINGALAYA
18  4MW24AD019             MOHAMMED SUHAN
19  4MW24AD020            MOHAMMED AFREED
13  4MW24AD014  GOURISH VENKATRAMAN MOGER
1   4MW24AD001          ADITHYA S POOJARY
23  4MW24AD024            NISHANTH SHETTY
56  4MW24AD058              ZEENATH ZIYAN
40  4MW24AD041               SAMANA G RAO
24  4MW24AD025                 PAVAN BHAT
21  4MW24AD022           MONISHA DEVADIGA
20  4MW24AD021        MOHAMMED AWAD TONSE
16  4MW24AD017      KISHAN GANAPATI HEGDE
9   4MW24AD010           BHEEMA KATTIMANI
5   4MW24AD005          ARPITHA M THANTRY
11  4MW24AD012            CHIRAG N KUNDER
25  4MW24AD026            PAVAN S POOJARY

                                 subject  total_classes  present  absent  \
0   Data Science & GenAI - 3nd Yr- AI&DS             11        0      11
52  Data Science & GenAI - 3nd Yr- AI&DS             10        0      10
58  Data Science & GenAI - 3nd Yr- AI&DS             10        0      10
36  Data Science & GenAI - 3nd Yr- AI&DS             10        0      10
45  Data Science & GenAI - 3nd Yr- AI&DS             10        0      10
61  Data Science & GenAI - 3nd Yr- AI&DS             10        1       9
26  Data Science & GenAI - 3nd Yr- AI&DS             11        3       8
30  Data Science & GenAI - 3nd Yr- AI&DS             10        3       7
8   Data Science & GenAI - 3nd Yr- AI&DS             11        4       7
31  Data Science & GenAI - 3nd Yr- AI&DS             10        5       5
37  Data Science & GenAI - 3nd Yr- AI&DS             10        5       5
59  Data Science & GenAI - 3nd Yr- AI&DS             10        5       5
10  Data Science & GenAI - 3nd Yr- AI&DS             11        6       5
41  Data Science & GenAI - 3nd Yr- AI&DS             10        6       4
55  Data Science & GenAI - 3nd Yr- AI&DS             10        6       4
60  Data Science & GenAI - 3nd Yr- AI&DS             10        6       4
17  Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
18  Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
19  Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
13  Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
1   Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
23  Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
56  Data Science & GenAI - 3nd Yr- AI&DS             10        7       3
40  Data Science & GenAI - 3nd Yr- AI&DS             10        7       3
24  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
21  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
20  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
16  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
9   Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
5   Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
11  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
25  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3

    excused  attendance_pct    status classes_needed_(75pct)  \
0         0             0.0  Critical                33 more
52        0             0.0  Critical                30 more
58        0             0.0  Critical                30 more
36        0             0.0  Critical                30 more
45        0             0.0  Critical                30 more
61        0            10.0  Critical                26 more
26        0            27.0  Critical                21 more
30        0            30.0  Critical                18 more
8         0            36.0  Critical                17 more
31        0            50.0  Critical                10 more
37        0            50.0  Critical                10 more
59        0            50.0  Critical                10 more
10        0            55.0  Critical                 9 more
41        0            60.0  Critical                 6 more
55        0            60.0  Critical                 6 more
60        0            60.0  Critical                 6 more
17        0            64.0  Critical                 5 more
18        0            64.0  Critical                 5 more
19        0            64.0  Critical                 5 more
13        0            64.0  Critical                 5 more
1         0            64.0  Critical                 5 more
23        0            64.0  Critical                 5 more
56        0            70.0  Critical                 2 more
40        0            70.0  Critical                 2 more
24        0            73.0  Critical                 1 more
21        0            73.0  Critical                 1 more
20        0            73.0  Critical                 1 more
16        0            73.0  Critical                 1 more
9         0            73.0  Critical                 1 more
5         0            73.0  Critical                 1 more
11        0            73.0  Critical                 1 more
25        0            73.0  Critical                 1 more

   last_present_date  consecutive_absences
0                NaT                    11
52               NaT                    10
58               NaT                    10
36               NaT                    10
45               NaT                    10
61        2026-09-02                     8
26        2026-10-05                     1
30        2026-10-07                     0
8         2026-10-05                     1
31        2026-10-05                     1
37        2026-10-05                     1
59        2026-10-07                     0
10        2026-10-07                     0
41        2026-10-05                     1
55        2026-10-07                     0
60        2026-10-05                     1
17        2026-10-07                     0
18        2026-10-07                     0
19        2026-10-07                     0
13        2026-10-07                     0
1         2026-10-07                     0
23        2026-10-07                     0
56        2026-10-07                     0
40        2026-10-07                     0
24        2026-10-07                     0
21        2026-10-07                     0
20        2026-10-07                     0
16        2026-10-07                     0
9         2026-10-07                     0
5         2026-10-07                     0
11        2026-10-07                     0
25        2026-10-07                     0

In [14]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('%', 'pct')

if 'present_days' in df.columns:
    absent_students = df[pd.to_numeric(df['present_days'], errors='coerce') == 0]
elif 'attendance_pct' in df.columns:
    absent_students = df[pd.to_numeric(df['attendance_pct'].astype(str).str.replace('%', '', regex=False), errors='coerce') == 0]
else:
    print(df.columns.tolist())
    raise KeyError("Present days or attendance percentage column not found.")

cols = [col for col in ['roll_no', 'student_name', 'consecutive_absences'] if col in df.columns]
print(absent_students[cols])

       roll_no            student_name  consecutive_absences
0    4MW23AD50               SRAJAN  S                    11
36  4MW24AD037  RISHAN FRANCIS MENEZES                    10
45  4MW24AD046           SHARANU PATIL                    10
52  4MW24AD054                UJWAL. K                    10
58  4MW24AD060        AMITH G PALANDYE                    10

In [15]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
print(df.loc[df['status'] == 'Safe'])

print(df.iloc[:15, 1:6])

       roll_no             student_name                               subject  \
2   4MW24AD002   ANKITHA PRASANNA NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
3   4MW24AD003           ANUSHA KOTEGAR  Data Science & GenAI - 3nd Yr- AI&DS
6   4MW24AD007                   ASNIYA  Data Science & GenAI - 3nd Yr- AI&DS
7   4MW24AD008    B. G PRARTHANA HEBBAR  Data Science & GenAI - 3nd Yr- AI&DS
14  4MW24AD015              K MANYA RAO  Data Science & GenAI - 3nd Yr- AI&DS
15  4MW24AD016                    KAVYA  Data Science & GenAI - 3nd Yr- AI&DS
28  4MW24AD029        PRATHEEKSHA NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
32  4MW24AD033            PRIYADARSHINI  Data Science & GenAI - 3nd Yr- AI&DS
33  4MW24AD034  RAKSHITHA (ASHOK KUMAR)  Data Science & GenAI - 3nd Yr- AI&DS
35  4MW24AD036            RAMITHA R RAO  Data Science & GenAI - 3nd Yr- AI&DS
39  4MW24AD040                   SAKSHI  Data Science & GenAI - 3nd Yr- AI&DS
42  4MW24AD043         SANJANA A MOOLYA  Data Science & GenAI - 3nd Yr- AI&DS
43  4MW24AD044          SANVI SHETTIGAR  Data Science & GenAI - 3nd Yr- AI&DS
44  4MW24AD045                 SHARADHI  Data Science & GenAI - 3nd Yr- AI&DS
46  4MW24AD047       SHETTY RAKSHA UDAY  Data Science & GenAI - 3nd Yr- AI&DS
47  4MW24AD048           SHRADDHA NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
48  4MW24AD049                  SHRAVYA  Data Science & GenAI - 3nd Yr- AI&DS
49  4MW24AD050         SHRI RAKSHA BHAT  Data Science & GenAI - 3nd Yr- AI&DS
50  4MW24AD052            TASMIYA ANJUM  Data Science & GenAI - 3nd Yr- AI&DS
51  4MW24AD053                  THRISHA  Data Science & GenAI - 3nd Yr- AI&DS
53  4MW24AD055         VAISHNAVI K AMIN  Data Science & GenAI - 3nd Yr- AI&DS
54  4MW24AD056       VANDANA V DEVADIGA  Data Science & GenAI - 3nd Yr- AI&DS
57  4MW24AD059              ZEHA AYESHA  Data Science & GenAI - 3nd Yr- AI&DS

    total_classes  present  absent  excused  attendance_pct status  \
2              11       11       0        0           100.0   Safe
3              11       10       1        0            91.0   Safe
6              11       10       1        0            91.0   Safe
7              11       10       1        0            91.0   Safe
14             11       10       1        0            91.0   Safe
15             11       11       0        0           100.0   Safe
28             11       11       0        0           100.0   Safe
32             10       10       0        0           100.0   Safe
33             10       10       0        0           100.0   Safe
35             10        9       1        0            90.0   Safe
39             10       10       0        0           100.0   Safe
42             10        9       1        0            90.0   Safe
43             10        9       1        0            90.0   Safe
44             10       10       0        0           100.0   Safe
46             10       10       0        0           100.0   Safe
47             10       10       0        0           100.0   Safe
48             10        9       1        0            90.0   Safe
49             10        9       1        0            90.0   Safe
50             10        9       1        0            90.0   Safe
51             10        9       1        0            90.0   Safe
53             10        9       1        0            90.0   Safe
54             10        9       1        0            90.0   Safe
57             10        9       1        0            90.0   Safe

   classes_needed_(75pct) last_present_date  consecutive_absences
2                   ✓ Met        2026-10-07                     0
3                   ✓ Met        2026-10-07                     0
6                   ✓ Met        2026-10-07                     0
7                   ✓ Met        2026-10-07                     0
14                  ✓ Met        2026-10-07                     0
15                  ✓ Met        2026-10-07                     0
28                  ✓ Met        2026-10-07                     0
32                  ✓ Met        2026-10-07                     0
33                  ✓ Met        2026-10-07                     0
35                  ✓ Met        2026-10-07                     0
39                  ✓ Met        2026-10-07                     0
42                  ✓ Met        2026-10-05                     1
43                  ✓ Met        2026-10-07                     0
44                  ✓ Met        2026-10-07                     0
46                  ✓ Met        2026-10-07                     0
47                  ✓ Met        2026-10-07                     0
48                  ✓ Met        2026-10-05                     1
49                  ✓ Met        2026-10-07                     0
50                  ✓ Met        2026-10-07                     0
51                  ✓ Met        2026-10-07                     0
53                  ✓ Met        2026-10-07                     0
54                  ✓ Met        2026-10-07                     0
57                  ✓ Met        2026-10-07                     0
                 student_name                               subject  \
0                   SRAJAN  S  Data Science & GenAI - 3nd Yr- AI&DS
1           ADITHYA S POOJARY  Data Science & GenAI - 3nd Yr- AI&DS
2      ANKITHA PRASANNA NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
3              ANUSHA KOTEGAR  Data Science & GenAI - 3nd Yr- AI&DS
4          ANVITA RAMESH NAIK  Data Science & GenAI - 3nd Yr- AI&DS
5           ARPITHA M THANTRY  Data Science & GenAI - 3nd Yr- AI&DS
6                      ASNIYA  Data Science & GenAI - 3nd Yr- AI&DS
7       B. G PRARTHANA HEBBAR  Data Science & GenAI - 3nd Yr- AI&DS
8          BHARATHRAJ A NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
9            BHEEMA KATTIMANI  Data Science & GenAI - 3nd Yr- AI&DS
10                      BINDU  Data Science & GenAI - 3nd Yr- AI&DS
11            CHIRAG N KUNDER  Data Science & GenAI - 3nd Yr- AI&DS
12                     DHANYA  Data Science & GenAI - 3nd Yr- AI&DS
13  GOURISH VENKATRAMAN MOGER  Data Science & GenAI - 3nd Yr- AI&DS
14                K MANYA RAO  Data Science & GenAI - 3nd Yr- AI&DS

    total_classes  present  absent
0              11        0      11
1              11        7       4
2              11       11       0
3              11       10       1
4              11        9       2
5              11        8       3
6              11       10       1
7              11       10       1
8              11        4       7
9              11        8       3
10             11        6       5
11             11        8       3
12             11        9       2
13             11        7       4
14             11       10       1

In [16]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
students = df[df['consecutive_absences'] >= 5]
print(students[['student_name', 'status', 'last_present_date']])

              student_name    status last_present_date
0                SRAJAN  S  Critical               NaT
36  RISHAN FRANCIS MENEZES  Critical               NaT
45           SHARANU PATIL  Critical               NaT
52                UJWAL. K  Critical               NaT
58        AMITH G PALANDYE  Critical               NaT
61        SAMPATH S HEBBAR  Critical        2026-09-02

### Section 3: Grouping & Aggregation

In [17]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
df.groupby('status').agg(
    student_count=('status', 'count'),
    average_attendance=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
)

          student_count  average_attendance  max_consecutive_absences
status
Critical             32           49.875000                        11
Safe                 23           94.086957                         1
Warning               7           81.428571                         1

In [18]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
df['attendance_category'] = pd.cut(
    df['attendance_pct'],
    bins=[-float('inf'), 60, 75, 90, float('inf')],
    labels=['Poor', 'Average', 'Good', 'Excellent'],
    right=False
)

print(df.groupby('attendance_category', observed=False).size())

attendance_category
Poor         13
Average      19
Good          7
Excellent    23
dtype: int64

In [21]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
df.agg({
    'total_classes': 'sum',
    'present': 'sum',
    'absent': 'sum'
})

total_classes    650
present          454
absent           196
dtype: int64

In [22]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
df.groupby('status').agg(
    present_min=('present', 'min'),
    present_max=('present', 'max'),
    present_mean=('present', 'mean'),
    absent_sum=('absent', 'sum')
)

          present_min  present_max  present_mean  absent_sum
status
Critical            0            8      5.312500         168
Safe                9           11      9.695652          14
Warning             8            9      8.714286          14

### Section 4: Feature Engineering & Transformation

In [23]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
df['risk_score'] = (df['absent'] * 0.4) + (df['consecutive_absences'] * 0.6)

print(df.sort_values(by='risk_score', ascending=False).head(10))

       roll_no            student_name                               subject  \
0    4MW23AD50               SRAJAN  S  Data Science & GenAI - 3nd Yr- AI&DS
36  4MW24AD037  RISHAN FRANCIS MENEZES  Data Science & GenAI - 3nd Yr- AI&DS
52  4MW24AD054                UJWAL. K  Data Science & GenAI - 3nd Yr- AI&DS
58  4MW24AD060        AMITH G PALANDYE  Data Science & GenAI - 3nd Yr- AI&DS
45  4MW24AD046           SHARANU PATIL  Data Science & GenAI - 3nd Yr- AI&DS
61  4MW25AD400        SAMPATH S HEBBAR  Data Science & GenAI - 3nd Yr- AI&DS
26  4MW24AD027                 PRAJWAL  Data Science & GenAI - 3nd Yr- AI&DS
8   4MW24AD009      BHARATHRAJ A NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
30  4MW24AD031         PRAVEEN KUMAR N  Data Science & GenAI - 3nd Yr- AI&DS
31  4MW24AD032           PREETH SHETTY  Data Science & GenAI - 3nd Yr- AI&DS

    total_classes  present  absent  excused  attendance_pct    status  \
0              11        0      11        0             0.0  Critical
36             10        0      10        0             0.0  Critical
52             10        0      10        0             0.0  Critical
58             10        0      10        0             0.0  Critical
45             10        0      10        0             0.0  Critical
61             10        1       9        0            10.0  Critical
26             11        3       8        0            27.0  Critical
8              11        4       7        0            36.0  Critical
30             10        3       7        0            30.0  Critical
31             10        5       5        0            50.0  Critical

   classes_needed_(75pct) last_present_date  consecutive_absences  \
0                 33 more               NaT                    11
36                30 more               NaT                    10
52                30 more               NaT                    10
58                30 more               NaT                    10
45                30 more               NaT                    10
61                26 more        2026-09-02                     8
26                21 more        2026-10-05                     1
8                 17 more        2026-10-05                     1
30                18 more        2026-10-07                     0
31                10 more        2026-10-05                     1

   attendance_category  risk_score
0                 Poor        11.0
36                Poor        10.0
52                Poor        10.0
58                Poor        10.0
45                Poor        10.0
61                Poor         8.4
26                Poor         3.8
8                 Poor         3.4
30                Poor         2.8
31                Poor         2.6

In [25]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
import re

col = next(c for c in df.columns if 'classes_needed' in c.lower().replace(' ', '_'))

df['classes_needed_numeric'] = (
    df[col].astype(str).str.extract(r'(\d+)')[0].fillna('0').astype(int)
)

print(df[['classes_needed_numeric']])

    classes_needed_numeric
0                       33
1                        5
2                        0
3                        0
4                        0
..                     ...
57                       0
58                      30
59                      10
60                       6
61                      26

[62 rows x 1 columns]

In [26]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
df['attendance_flag'] = df['attendance_pct'].apply(lambda x: 'Defaulter' if x < 75 else 'Safe')

print(df[['attendance_pct', 'attendance_flag']])

    attendance_pct attendance_flag
0              0.0       Defaulter
1             64.0       Defaulter
2            100.0            Safe
3             91.0            Safe
4             82.0            Safe
..             ...             ...
57            90.0            Safe
58             0.0       Defaulter
59            50.0       Defaulter
60            60.0       Defaulter
61            10.0       Defaulter

[62 rows x 2 columns]

In [27]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
df['attendance_range'] = pd.cut(
    df['attendance_pct'],
    bins=[0, 50, 75, 90, 100],
    labels=['Critical', 'Warning', 'Good', 'Excellent'],
    include_lowest=True
)

print(df[['attendance_pct', 'attendance_range']])

    attendance_pct attendance_range
0              0.0         Critical
1             64.0          Warning
2            100.0        Excellent
3             91.0        Excellent
4             82.0             Good
..             ...              ...
57            90.0             Good
58             0.0         Critical
59            50.0         Critical
60            60.0          Warning
61            10.0         Critical

[62 rows x 2 columns]

### Section 5: Advanced Analysis

In [28]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
pd.pivot_table(
    df,
    index='status',
    columns='attendance_category',
    values='student_name',
    aggfunc='count',
    fill_value=0
)

attendance_category  Poor  Average  Good  Excellent
status
Critical               13       19     0          0
Safe                    0        0     0         23
Warning                 0        0     7          0

In [29]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
df['base_name'] = df['student_name'].str.extract(r'^([A-Z]+)')

duplicate_names = df[df.duplicated(subset='base_name', keep=False)]

print(duplicate_names.sort_values(by='base_name'))

       roll_no                student_name  \
18  4MW24AD019              MOHAMMED SUHAN
19  4MW24AD020             MOHAMMED AFREED
20  4MW24AD021         MOHAMMED AWAD TONSE
24  4MW24AD025                  PAVAN BHAT
25  4MW24AD026             PAVAN S POOJARY
33  4MW24AD034     RAKSHITHA (ASHOK KUMAR)
34  4MW24AD035  RAKSHITHA(RAMESHA POOJARI)

                                 subject  total_classes  present  absent  \
18  Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
19  Data Science & GenAI - 3nd Yr- AI&DS             11        7       4
20  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
24  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
25  Data Science & GenAI - 3nd Yr- AI&DS             11        8       3
33  Data Science & GenAI - 3nd Yr- AI&DS             10       10       0
34  Data Science & GenAI - 3nd Yr- AI&DS             10        8       2

    excused  attendance_pct    status classes_needed_(75pct)  \
18        0            64.0  Critical                 5 more
19        0            64.0  Critical                 5 more
20        0            73.0  Critical                 1 more
24        0            73.0  Critical                 1 more
25        0            73.0  Critical                 1 more
33        0           100.0      Safe                  ✓ Met
34        0            80.0   Warning                  ✓ Met

   last_present_date  consecutive_absences attendance_category  risk_score  \
18        2026-10-07                     0             Average         1.6
19        2026-10-07                     0             Average         1.6
20        2026-10-07                     0             Average         1.2
24        2026-10-07                     0             Average         1.2
25        2026-10-07                     0             Average         1.2
33        2026-10-07                     0           Excellent         0.0
34        2026-10-05                     1                Good         1.4

    classes_needed_numeric attendance_flag attendance_range  base_name
18                       5       Defaulter          Warning   MOHAMMED
19                       5       Defaulter          Warning   MOHAMMED
20                       1       Defaulter          Warning   MOHAMMED
24                       1       Defaulter          Warning      PAVAN
25                       1       Defaulter          Warning      PAVAN
33                       0            Safe        Excellent  RAKSHITHA
34                       0            Safe             Good  RAKSHITHA

In [30]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
Student_Details = pd.DataFrame({
    'roll_no': df['roll_no'],
    'branch': ['AI&DS'] * len(df),
    'semester': [5] * len(df)
})

merged_df = pd.merge(df, Student_Details, on='roll_no', how='inner')

print(merged_df)

       roll_no            student_name                               subject  \
0    4MW23AD50               SRAJAN  S  Data Science & GenAI - 3nd Yr- AI&DS
1   4MW24AD001       ADITHYA S POOJARY  Data Science & GenAI - 3nd Yr- AI&DS
2   4MW24AD002  ANKITHA PRASANNA NAYAK  Data Science & GenAI - 3nd Yr- AI&DS
3   4MW24AD003          ANUSHA KOTEGAR  Data Science & GenAI - 3nd Yr- AI&DS
4   4MW24AD004      ANVITA RAMESH NAIK  Data Science & GenAI - 3nd Yr- AI&DS
..         ...                     ...                                   ...
57  4MW24AD059             ZEHA AYESHA  Data Science & GenAI - 3nd Yr- AI&DS
58  4MW24AD060        AMITH G PALANDYE  Data Science & GenAI - 3nd Yr- AI&DS
59  4MW24AD061      AMOGH BHASKAR NAIK  Data Science & GenAI - 3nd Yr- AI&DS
60  4MW24AD062                CHANDISH  Data Science & GenAI - 3nd Yr- AI&DS
61  4MW25AD400        SAMPATH S HEBBAR  Data Science & GenAI - 3nd Yr- AI&DS

    total_classes  present  absent  excused  attendance_pct    status  \
0              11        0      11        0             0.0  Critical
1              11        7       4        0            64.0  Critical
2              11       11       0        0           100.0      Safe
3              11       10       1        0            91.0      Safe
4              11        9       2        0            82.0   Warning
..            ...      ...     ...      ...             ...       ...
57             10        9       1        0            90.0      Safe
58             10        0      10        0             0.0  Critical
59             10        5       5        0            50.0  Critical
60             10        6       4        0            60.0  Critical
61             10        1       9        0            10.0  Critical

   classes_needed_(75pct) last_present_date  consecutive_absences  \
0                 33 more               NaT                    11
1                  5 more        2026-10-07                     0
2                   ✓ Met        2026-10-07                     0
3                   ✓ Met        2026-10-07                     0
4                   ✓ Met        2026-10-07                     0
..                    ...               ...                   ...
57                  ✓ Met        2026-10-07                     0
58                30 more               NaT                    10
59                10 more        2026-10-07                     0
60                 6 more        2026-10-05                     1
61                26 more        2026-09-02                     8

   attendance_category  risk_score  classes_needed_numeric attendance_flag  \
0                 Poor        11.0                      33       Defaulter
1              Average         1.6                       5       Defaulter
2            Excellent         0.0                       0            Safe
3            Excellent         0.4                       0            Safe
4                 Good         0.8                       0            Safe
..                 ...         ...                     ...             ...
57           Excellent         0.4                       0            Safe
58                Poor        10.0                      30       Defaulter
59                Poor         2.0                      10       Defaulter
60             Average         2.2                       6       Defaulter
61                Poor         8.4                      26       Defaulter

   attendance_range base_name branch  semester
0          Critical    SRAJAN  AI&DS         5
1           Warning   ADITHYA  AI&DS         5
2         Excellent   ANKITHA  AI&DS         5
3         Excellent    ANUSHA  AI&DS         5
4              Good    ANVITA  AI&DS         5
..              ...       ...    ...       ...
57             Good      ZEHA  AI&DS         5
58         Critical     AMITH  AI&DS         5
59         Critical     AMOGH  AI&DS         5
60          Warning  CHANDISH  AI&DS         5
61         Critical   SAMPATH  AI&DS         5

[62 rows x 20 columns]

In [32]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
df[df['status'] == 'Critical'].to_csv('critical_students.csv', index=False)

df.groupby('status').agg(
    student_count=('status', 'count'),
    average_attendance=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
).to_csv('status_summary.csv')

df.sort_values(by='risk_score', ascending=False).head(10).to_csv('top_10_risk_students.csv', index=False)